package com.complipilot.backend.notification.enums;

public enum NotificationType {
    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    EVIDENCE_CREATED,
    EVIDENCE_ARCHIVED,
    AI_ANALYSIS_COMPLETED,
    TASK_CREATED,
    TASK_ASSIGNED,
    COMPLIANCE_ITEM_UPDATED,
    BILLING_PLAN_CHANGE_REQUESTED,
    BILLING_PLAN_CHANGE_APPROVED,
    BILLING_PLAN_CHANGE_REJECTED,
    BILLING_PLAN_CHANGE_CANCELLED
}