package com.complipilot.backend.audit.enums;

public enum AuditAction {
    COMPLIANCE_FRAMEWORK_APPLIED,
    COMPLIANCE_ITEM_CREATED,
    COMPLIANCE_ITEM_UPDATED,
    EVIDENCE_DOCUMENT_CREATED,
    EVIDENCE_DOCUMENT_UPDATED,
    EVIDENCE_DOCUMENT_ARCHIVED,
    EVIDENCE_LINK_CREATED,
    EVIDENCE_LINK_DELETED,
    COMPLIANCE_TASK_CREATED,
    COMPLIANCE_TASK_UPDATED,
    COMPLIANCE_TASK_DELETED,
    ORGANIZATION_DISABLED,
    BILLING_PLAN_CHANGE_REQUESTED,
    BILLING_PLAN_CHANGE_APPROVED,
    BILLING_PLAN_CHANGE_REJECTED,
    BILLING_PLAN_CHANGE_CANCELLED
}